site_name: 'Example'
site_description: 'Example documentation'
repo_url: https://github.com/callebstrom/example-entities
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Home: 'index.md'
